# GitHub Actions Workflow for Building and Releasing the NREGA Bot
#
# This workflow automates the entire build process for the Windows installer.
# It now automatically uses the changelog.json file for the release notes.

name: Build and Release Installer

on:
  push:
    tags:
      - 'v*' # Triggers on tags like v1.0, v2.5.3, etc.

jobs:
  build:
    runs-on: windows-latest

    steps:
      # Step 1: Checks-out your repository
      - name: Checkout repository
        uses: actions/checkout@v4

      # Step 2: Sets up Python
      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.9'

      # Step 3: Installs Inno Setup
      - name: Setup Inno Setup
        uses: crazy-max/ghaction-inno-setup@v3
        with:
          version: "latest"

      # Step 4: Install Python dependencies
      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt

      # Step 5: Generate the branded BMP wizard images
      - name: Generate wizard images
        run: python generate_wizard_images.py

      # Step 6: Run the main build script to create the installer
      - name: Build the application
        run: ./build_windows.bat
        shell: cmd

      # --- NEW STEP ---
      # Step 7: Generate release notes from the changelog
      - name: Generate Release Notes
        run: python extract_changelog.py ${{ github.ref_name }}
        # ${{ github.ref_name }} provides the tag that triggered the workflow (e.g., "v2.5.3")

      # --- UPDATED STEP ---
      # Step 8: Create a formal GitHub Release with the installer and notes
      - name: Create GitHub Release
        uses: softprops/action-gh-release@v2
        with:
          # Use the generated releasenotes.md file as the body for the release
          body_path: releasenotes.md
          files: |
            installer/NREGABot-v*-Setup.exe
